version: "3.3"

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    image: app/api
  client:
    build:
      context: .
      dockerfile: Dockerfile.client
    image: app/client
    ports:
      - "3000:80"