# This Dockerfile builds API only

FROM python:3.9
WORKDIR /app

COPY ./my_lib ./my_lib
COPY ./setup.py ./pyproject.toml ./
COPY ./app/api/api.py ./app/api/requirements.txt ./app/api/.flaskenv ./

RUN pip install -r ./requirements.txt
RUN pip install . 

ENV FLASK_ENV production

EXPOSE 1234
CMD ["gunicorn", "-b", ":1234", "api:app"]
